blueconnect: Move to qt5-layer
This prevents the blueconnect recipe from being parsed in situations
where the qt5 layer is not available.

The present location of the recipe introduces the following error in
projects which do not include meta-qt5:
ERROR: ParseError at
<PATH>meta-bistro/recipes-connectivity/blueconnect/blueconnect_git.bb:31: Could not inherit file classes/qmake5.bbclass

Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>